spring.application.name=warehouse-backend
spring.datasource.url=jdbc:postgresql://db:5432/test_db
spring.datasource.username=root
spring.datasource.password=root
app.resource.inventory=classpath:data/inventory.json
app.resource.product=classpath:data/products.json
spring.jpa.hibernate.ddl-auto=update